---

- name: Including secret configurations, if necessary
  include_vars: "vault/secrets.yml"
  when: hm_firewalled__ssh_restrict_to_host or hm_firewalled__allow_workstations

- block:

    - name: Resetting firewall to installation defaults
      ufw:
        state: reset
        policy: allow

    - name: Disabling firewall
      ufw:
        state: disabled

  when: hm_firewalled__flush_and_reload

- name: Opening SSH port for general access
  ufw:
    rule: allow
    port: "{{ hm_firewalled__ssh_port }}"
    proto: tcp
  when: not hm_firewalled__ssh_restrict_to_host

- block:

    #
    # Make sure all users are stil able to access the server.
    #
    - include: _func.ufw_open_port.yml
      vars:
        ri_label: "SSH access for user {{ outer_item.key }}"
        ri_ufw_open_port: "{{ hm_firewalled__ssh_port }}"
        ri_ufw_open_ips: "{{ outer_item.value.workstations }}"
      with_dict: "{{ site_users }}"
      loop_control:
        loop_var: outer_item
      when: outer_item.key in hm_accounts__admins or outer_item.key in hm_accounts__users

  when: hm_firewalled__ssh_restrict_to_host

#-------------------------------------------------------------------------------

- name: Enabling remote monitoring for appropriate hosts
  ufw:
    rule: allow
    port: "{{ hm_monitored__service_port }}"
    from_ip: "{{ item }}"
  with_items: "{{ hm_monitored__allowed_hosts }}"
  when: '"servers_monitored" in group_names'

#-------------------------------------------------------------------------------

- name: Opening custom ports for general access
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items: "{{ hm_firewalled__open_ports }}"

- name: Allowing general access for custom hosts
  ufw:
    rule: allow
    from_ip: "{{ item }}"
  with_items: "{{ hm_firewalled__allow_hosts }}"

#-------------------------------------------------------------------------------

# Opening all ports for listed user workstations

- include: _func.ufw_open_all.yml
  vars:
    ri_label: "FULL access for user {{ outer_item }}"
    ri_ufw_open_ips: "{{ site_users[outer_item]['workstations'] }}"
  with_list: "{{ hm_firewalled__allow_workstations }}"
  loop_control:
    loop_var: outer_item

#-------------------------------------------------------------------------------

# Opening listed ports for listed hosts

- include: _func.ufw_open_port.yml
  vars:
    ri_label: "custom-rule"
    ri_ufw_open_port: "{{ outer_item.key }}"
    ri_ufw_open_ips: "{{ outer_item.value }}"
  with_dict: "{{ hm_firewalled__open_port_hosts }}"
  loop_control:
    loop_var: outer_item

#-------------------------------------------------------------------------------

- name: Enabling logging
  ufw:
    logging: on

- name: Enabling firewall
  ufw:
    state: enabled
    policy: deny
